### ISSUE TITLE
[27-5] 추방되기 전 게스트가 방에서 나갔다면, 호스트에게 '이미 나간 참여자입니다.' 메시지를 전송

### ISSUE THREAD

**Issue by Dev-Beom** [boostcampwm-2021/web15-TadakTadak#107]
## Story
> 호스트가 게스트를 추방할 때 게스트가 이미 방에서 나간 상태라면
이미 나간 상태라는걸 표시해줘야함.

## Progress
- [ ] ~이미 나간 상태라는 것을 표시할 컴포넌트(toast Message)~
- [ ] ~이미 나간 상태인지 확인하는 로직~

**Comment by jiho-bae** [comment]
wasted
