### ISSUE TITLE
[53-1]  화면공유를 한 박스를 더블클릭하면 전체화면으로 변경

### ISSUE THREAD

**Issue by jiho-bae** [boostcampwm-2021/web15-TadakTadak#206]
## Story
화면공유를 한 박스를 더블클릭하면 전체화면으로 변경

## Progress
- [x] 캠과 화면공유의 스트림을 구분한다.
- [x] 박스를 더블클릭 할 때 전체화면으로 변경한다.
- [x]  ESC 버튼을 통해 전체화면을 탈출한다.

**Comment by jiho-bae** [comment]
캠과 화면공유와 스트림을 구분할 마땅한 키가 없는 상태입니다.

**Comment by Narastro** [comment]
스트림을 구분하지 않고 전체화면 기능을 넣었습니다.
