### ISSUE TITLE
방 인원 집계 문제

### ISSUE THREAD

**Issue by jiho-bae** [boostcampwm-2021/web15-TadakTadak#250]
### 현재 버그/이슈에 대한 간단한 설명
- 유저가 방에서 퇴장 시 방 인원 감소 요청이 2회 혹은 그 이상 발생하는 문제

### 버그 재현 방법 요약
- 유저가 정상적인 방법(나가기 버튼 / 브라우저의 뒤로 가기)이 아닌 방법으로 퇴장 시 발생한다.
- 유저가 새로고침을 통해 방에서 나가면 방 인원이 -1이 되는 것이 아니라 -2가 된다.

### 정상 동작시 예상되는 동작
- 유저가 방에서 퇴장시 방 인원은 -1이 되어야 한다.

**Comment by Dev-Beom** [comment]
> 유저가 정상적인 방법(나가기 버튼 / 브라우저의 뒤로 가기)이 아닌 방법으로 퇴장 시 발생한다.
는 서버사이드에서 해결할 수 있으나
> 유저가 새로고침을 통해 방에서 나가면 방 인원이 -1이 되는 것이 아니라 -2가 된다.
는 잘모르겠네요
