### ISSUE TITLE
게스트가 방에서 새로고침 시 소켓에 남아있는 문제

### ISSUE THREAD

**Issue by jiho-bae** [boostcampwm-2021/web15-TadakTadak#253]
### 현재 버그/이슈에 대한 간단한 설명
게스트가 방에서 새로고침 시 게스트는 메인페이지로 이동되지만, 방 소켓에는 남아있습니다.

### 버그 재현 방법 요약
- 게스트가 방에서 새로고침을 시도
- 게스트는 history.replace에 의해 메인페이지로 이동된다.
- 방에서 Agora 스트림은 사라지지만, 방 소켓(참여자 리스트)에 남아있다.

### 정상 동작시 예상되는 동작
- 게스트가 새로고침을 하면 Agora 스트림이 사라지고, 방 소켓에서도 사라져야 한다.

**Comment by Narastro** [comment]
새로고침시 메인으로 튕기게 하여 해결하였습니다.
