### ISSUE TITLE
[6-4] 코딩 라이브 탭

### ISSUE THREAD

**Issue by Narastro** [boostcampwm-2021/web15-TadakTadak#34]
## Story

>6. 메인 탭을 이용해 3가지 타입의 방을 선택할 수 있다.

## Progress
- [ ] 메인 리스트 상단에 코딩 라이브 탭을 생성한다
- [ ] 탭을 누르면 코딩라이브 방을 필터하여 보여준다

**Comment by jiho-bae** [comment]
closed
